app = "gitcoin-search-dev"
primary_region = "den"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]

[env]
  DEPLOYMENT_ENVIRONMENT = "development"
  CHROMADB_PERSISTENCE_DIR= "/tmp/chromadb"
  LOG_LEVEL = "debug"
  PORT = "8000"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "30s"
    timeout = "10s"
    grace_period = "1m0s"
