app = "gitcoin-search-dev"
primary_region = "den"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]

[env]
  DEPLOYMENT_ENVIRONMENT = "development"
  LOG_LEVEL = "debug"
  PORT = "8000"
  STORAGE_DIR = "/tmp/data"
  APPLICATION_FILES_LOCATORS = "10:0x10be322DE44389DeD49c0b2b73d8c3A1E3B6D871,10:0xc5FdF5cFf79e92FAc1d6Efa725c319248D279200,10:0x9331FDe4Db7b9d9d1498C09d30149929f24cF9D5,10:0xb6Be0eCAfDb66DD848B0480db40056Ff94A9465d,10:0x2871742B184633f8DC8546c6301cbC209945033e,10:0x8de918F0163b2021839A8D84954dD7E8e151326D"
  BIND_ADDRESS = "0.0.0.0"
  HTTP_WORKERS = "4"
  ANONYMIZED_TELEMETRY = "False"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "30s"
    timeout = "10s"
    grace_period = "1m0s"
    
  # [[services.http_checks]]
  #   interval = "60s"
  #   grace_period = "1m"
  #   timeout = "5s"
  #   method = "get"
  #   path = "/ping"
  #   protocol = "http"
